### ISSUE TITLE
Enhance task editing capabilities by allowing users to select tasks using TTDL and edit them in a text editor

### ISSUE THREAD

**Issue by 83noit** [VladimirMarkelov/ttdl#101]
Enhance task editing capabilities by allowing users to select tasks using TTDL and edit them directly in a text editor like _visudo_ or _edit-command-line_ in ZSH. The edited tasks could be validated before committing the changes, ensuring data integrity and preventing accidental modifications to the human-readable todo.txt format. The editor could default the environment variable or be specified in the configuration otherwise.

For example:
```
# ttdl edit -e @foo
ttdl edit -e 512 
# -> Opens Vim with the subset of tasks in a temporary files
# -> :wq on the temporary file validates the format and commits. :q! discards the pending changes. 
```

**Comment by VladimirMarkelov** [comment]
I thought about calling an external editor before. But only to edit either one task or the whole file. It is not clear what to do in case of editing a set of tasks.

> :wq on the temporary file validates the format and commits. :q! discards the pending changes.

Two comments: 

- `:q!` works only if it is the only command after editing. Case: first, a person does `:w` and then `:q!`. In this case, I think the task list must be updated because I have no clue how to tell `:wq` from `:w` and `:q!`
- `validates the format` - validates what? Currently, any sequence of characters is a valid task

> .. and commits

In case of the entire file or a single task, it is clear what to do. Let's assume `ttdl edit -e @foo` opened a few tasks. You delete one task, swap two others, and then edit them (e.g, replace `@foo` with `@bar`). What TTDL should do after `:wq`? The only operation I could imagine is to: first, delete old tasks; second, append the content of edited file to the result. It changes the internal IDs of tasks but this way is kind of error-proof and easy. I am not sure if it is always an expected behavior.

The last question: in case of a person deletes all lines and saves the empty file. TTDL should just delete old lines? TTDL should do nothing?

**Comment by 83noit** [comment]
The vim commands in my example are illustrative and too specific. The trigger for TTDL would be a change in the temporary scratchpad, or do nothing otherwise.

The delete and append, with the caveat of the change of IDs, sounds like acceptable trade-off imho if this is documented.

Modification of the whole file. I could think of two options:
- Same policy as `ttdl e --set-foo bar`
- Prevent it by default on the basis that there are safer alternatives to empty a file.

**Comment by VladimirMarkelov** [comment]
It makes sense. Maybe, instead of forbidding to edit all tasks - that can be useful at times, just treat empty resulting file as a non-modified one. If I am not mistaken, git does the same: if you save an empty file for a commit description, it aborts the operation.

**Comment by VladimirMarkelov** [comment]
Added a way to edit tasks in an external editor in `v4.6.0`
