### ISSUE TITLE
Add ability to load config file from a given path

### ISSUE THREAD

**Issue by murlakatamenka** [VladimirMarkelov/ttdl#22]
Suggested syntax:
```sh
ttdl -c|--config <path-to-config>
```
For reference `todo.sh` uses `-d` to load its config, `-c` is for color in its case.

Other thing I'd suggest is to move config file to a separate folder, i.e. to `~/.config/ttdl/ttdl.toml`. Yes, it's just a single config file, but there is normally enough system-generated stuff inside `~/.config` so it's nice to have important for user settings inside a corresponding application folder. This is subjective, of course, but I'd welcome such change and call it an improvement.

**Comment by VladimirMarkelov** [comment]
I agree with both suggestions. Moreover, I thought of allowing a user to pass config file path in command line. But I was unsure if anyone needs it. Since, now I am not the only one who thinks of the feature, I'll implement it.

The other suggestion I moved to separate ticket #23 - to keep this one only for '-c|--config' option
