### ISSUE TITLE
Default apply threshold filter "none..today"

### ISSUE THREAD

**Issue by SevereOverfl0w** [VladimirMarkelov/ttdl#50]
Threshold is used to hide tasks I can't deal with for a few days.  It would be useful therefore if `--threshold none..today` was applied by default when running `ttdl list` unless I specifically override it by supplying `--threshold`, e.g. `ttdl --threshold=tomorrow`.

**Comment by VladimirMarkelov** [comment]
Good to know. Thanks for the explanation. I never used threshold and it was unclear to me how people use it.

**Comment by VladimirMarkelov** [comment]
`threshold` uses default range `none..today` since version `2.1.0`

**Comment by SevereOverfl0w** [comment]
Nice!  Although I _may_ have misunderstood how the filters worked, and it should be `none..yesterday`.  The way it works is that if for the date I'm posting this issue (2021-09-26) the todo had `t:2021-09-26` it should show up, but `t:2021-09-27` wouldn't.  I should probably have just specified this instead of what I thought the filter should be.

**Comment by VladimirMarkelov** [comment]
From the current docs: "Ranges are always inclusive". If I understood the threshold idea correctly, threshold was "The day from which the task must appear in the list". Example: for `t:2021-09-26` and the current day `2021-09-26`, the range `none..today` must include the record. Because `today` is one of the range ends. But I am not saying that my understanding is correct :) I do not remember reading an explanation of how threshold should work when I implemented it.

Before version `2.1` one must use `threshold=none..tomorrow` filter to get the same result. It seems a bit inconvenient to me because to include tomorrow one have use more cryptic `threshold=none..2d`.

**Comment by SevereOverfl0w** [comment]
It sounds correct, sounds like you've changed the behaviour to match what I expected!
