### ISSUE TITLE
--compact removes colors

### ISSUE THREAD

**Issue by onsamyj** [VladimirMarkelov/ttdl#67]
If I use `ttdl`, or `ttdl --human`, `ttdl l --human=due`, etc., projects, due dates, contexts, etc. are highlighted in their respective colors, which I set in ttdl.toml.

But if I add `--compact` to any of these commands, everything is white, except for priorities (`--no-colors` also removes the color for priorities).

**Comment by VladimirMarkelov** [comment]
Fixed in this commit: https://github.com/VladimirMarkelov/ttdl/commit/fffaa1cb5c2a453f0a5991c8f623cda2d0fda55f

The following commit was only to fix the code according to the warnings by the latest `clippy` - it is not an obligatory commit to fetch if you are going to build yourself.

I've published the new crate at crates.io, but I haven't published new git release as I want to complete #66 as well before. Anyway, if you need a ready-to-use binary, let me know and I'll build linux+windows ones and publish a new release.

**Comment by onsamyj** [comment]
While I do need a binary (I use [Scoop](https://scoop.sh)), it is not urgent, feel free to fix other bugs first.

Thanks!

**Comment by VladimirMarkelov** [comment]
Released v3.6.2 - https://github.com/VladimirMarkelov/ttdl/releases/tag/v3.6.2
