### ISSUE TITLE
`ttdl done` marks all tasks as done

### ISSUE THREAD

**Issue by arthurbdev** [VladimirMarkelov/ttdl#92]
I don't know if it's intended behaviour but `ttdl done` without any arguments marks all tasks as done. 

**Edit:** Just tested it out, `ttdl rm` without any arguments wipes out all the undone tasks. 
I think there needs to be a check if any arguments are provided before processing the command.

**Comment by VladimirMarkelov** [comment]
Thank you for the report. It was by design but it was not intended: all commands share the same task ID list processing without exceptions. In my opinion, no argument makes sense only for `ls` command. The rest commands must require a filter from a user. Otherwise, it is easy to ruin a todo list by running `edit` or `rm` for all tasks.

**Comment by VladimirMarkelov** [comment]
Now a few commands are forbidden to run without specifying tasks to process.

Version `4.2.1` published on `crates.io`. Releases updated.
